global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-api'
    static_configs:
      - targets: ['user-api:9394']
  - job_name: 'voting-api'
    static_configs:
      - targets: ['voting-api:9395']