global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-api'
    dns_sd_configs:
      - names: ['tasks.user-api']
        type: A
        port: 9394

  - job_name: 'voting-api'
    dns_sd_configs:
      - names: ['tasks.voting-api']
        type: A
        port: 9395