require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/**/*'
    - 'test/**/*'


Rails:
  Enabled: true