name: PostgreSQL Backup
#no longer in use
on:
  schedule:
    - cron: '0 17 * * *'  # run at 6pm UTC every day
  workflow_dispatch:

jobs:
  backup-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: user_api_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Wait for PostgreSQL..."
          sleep 5
        done

    - name: Run backup inside of the container
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        mkdir -p backups
        docker run --rm \
            --network host \
            -e PGPASSWORD=password \
            postgres:17.4 \
            pg_dump -h localhost -U postgres -d user_api_development > backups/backup_$TIMESTAMP.sql

    - name: Archive backup
      run: tar -czvf db_backup.tar.gz backups/

    - name: Upload backup as artifact
      uses: actions/upload-artifact@v4
      with:
        name: postgres-db-backup
        path: db_backup.tar.gz

    - name: Setup rclone
      uses: wei/rclone-action@v2
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
  
    - name: Upload backup to Google Drive with rclone
      env:
        RCLONE_CONFIG_GDRIVE: ${{ secrets.RCLONE_CONFIG }}
      run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
          rclone copy db_backup.tar.gz gdrive:/database_backups/