name: PostgreSQL Backup
#no longer in use
on:
  schedule:
    - cron: '0 17 * * *'  # run at 6pm UTC every day
  workflow_dispatch:

jobs:
  backup-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: user_api_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Wait for PostgreSQL..."
          sleep 5
        done

    - name: Run backup inside of the container
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        mkdir -p backups
        docker run --rm \
            --network host \
            -e PGPASSWORD=password \
            postgres:17.4 \
            pg_dump -h localhost -U postgres -d user_api_development > backups/backup_$TIMESTAMP.sql
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Archive backup
      run: |
        tar -czvf db_backup_${{ env.TIMESTAMP }}.tar.gz backups/
        echo "BACKUP_FILE=db_backup_${{ env.TIMESTAMP }}.tar.gz" >> $GITHUB_ENV

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
      
    - name: Configure rclone
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
      
    - name: Upload backup to Google Drive
      run: |
        rclone copy $BACKUP_FILE google_drive:/database_backups/