name: Build and Push to Docker Hub

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the infrastructure?'
        required: false
        default: 'false'
      rollback_version:
        description: 'Version to rollback to (leave blank to deploy new)'
        required: false
        default: ''

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify Slack of workflow started 
      if: always()
      run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \" *Deployment Started*\n*Workflow:* ${{ github.workflow }}\n*Branch:* ${{ github.ref_name }}\n*Initiated by:* ${{ github.actor }}\n*Rollback:* ${{ github.event.inputs.rollback_version != '' && 'Yes' || 'No' }}\n*Destroy:* ${{ github.event.inputs.destroy == 'true' && 'Yes' || 'No' }}\"
          }" ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Set up Git authentication
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set version tag using timestamp
      id: vars
      run: echo "VERSION=$(date +%s)" >> "$GITHUB_ENV"

    - name: Save version tag to artifact
      run: echo "${{ env.VERSION }}" > version.txt
    
    - name: Upload version artifact
      uses: actions/upload-artifact@v4
      with:
        name: version-tag
        path: version.txt

    - name: Save current version to tracked file
      run: echo "${{ env.VERSION }}" > ./terraform/last_version.txt
      
    - name: Git pull version file
      if: github.event.inputs.rollback_version == ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git stash --include-untracked
          git pull --rebase origin master
          git stash pop || echo "No stash to apply"
    
    - name: Save and commit version info
      if: github.event.inputs.rollback_version == ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ env.VERSION }}" > ./terraform/last_version.txt
        git add -f ./terraform/last_version.txt
        git commit -m "Track last deployed version: ${{ env.VERSION }}" || echo "Nothing to commit"
        git push origin master

      # Execute the rollback
    - name: Override version for rollback if specified
      if: github.event.inputs.rollback_version != ''
      run: |
          echo "ROLLBACK VERSION SELECTED: ${{ github.event.inputs.rollback_version }}"
          echo "VERSION=${{ github.event.inputs.rollback_version }}" >> "$GITHUB_ENV"

    # Build user-api image (no push yet)
    - name: Build user-api
      if: github.event.inputs.rollback_version == ''
      id: build_user_api
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USER_IMAGE_NAME }}:${{ env.VERSION }} ./${{ secrets.USER_CONTEXT }}

    # Build voting-api image (no push yet)
    - name: Build voting-api
      if: github.event.inputs.rollback_version == ''
      id: build_voting_api
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_VOTING_IMAGE_NAME }}:${{ env.VERSION }} ./${{ secrets.VOTING_CONTEXT }}

    # Build frontend image (no push yet)
    - name: Build frontend-blue
      if: github.event.inputs.rollback_version == ''
      id: build_frontend_blue
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:blue${{ env.VERSION }} ./${{ secrets.FRONTEND_CONTEXT }}

    # Build frontend image (no push yet)
    - name: Build frontend-green
      if: github.event.inputs.rollback_version == ''
      id: build_frontend_green
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:green${{ env.VERSION }} ./${{ secrets.FRONTEND_CONTEXT }}

    # Install Trivy for vulnerability scanning
    - name: Install Trivy for vulnerability scanning
      if: github.event.inputs.rollback_version == ''
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.tar.gz | tar -xzv
        sudo mv trivy /usr/local/bin/

    # Scan the user-api Docker image for vulnerabilities
    - name: Scan Docker image with Trivy - User api
      if: github.event.inputs.rollback_version == ''
      run: trivy image --exit-code 0 --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USER_IMAGE_NAME }}:${{ env.VERSION }} > user-api-trivy-report.json

    # Upload the user Trivy scan report as an artifact
    - name: Upload Trivy scan report as artifact - User api
      if: github.event.inputs.rollback_version == ''
      uses: actions/upload-artifact@v4
      with:
        name: user-api-trivy-report
        path: user-api-trivy-report.json

    # Scan the voting-api Docker image for vulnerabilities
    - name: Scan Docker image with Trivy - Voting api
      if: github.event.inputs.rollback_version == ''
      run: trivy image --exit-code 0 --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_VOTING_IMAGE_NAME }}:${{ env.VERSION }} > voting-api-trivy-report.json

    # Upload the voting Trivy scan report as an artifact
    - name: Upload Trivy scan report as artifact - Voting api
      if: github.event.inputs.rollback_version == ''
      uses: actions/upload-artifact@v4
      with:
        name: voting-api-trivy-report
        path: voting-api-trivy-report.json

    # Scan the frontend Docker image for vulnerabilities
    - name: Scan Docker image with Trivy - Frontend blue
      if: github.event.inputs.rollback_version == ''
      run: trivy image --exit-code 0 --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:blue${{ env.VERSION }} > frontend-blue-trivy-report.json

    # Upload the frontend Trivy scan report as an artifact
    - name: Upload Trivy scan report as artifact - Frontend blue
      if: github.event.inputs.rollback_version == ''
      uses: actions/upload-artifact@v4
      with:
        name: frontend-blue-trivy-report
        path: frontend-blue-trivy-report.json

    # Scan the frontend Docker image for vulnerabilities
    - name: Scan Docker image with Trivy - Frontend green
      if: github.event.inputs.rollback_version == ''
      run: trivy image --exit-code 0 --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:green${{ env.VERSION }} > frontend-green-trivy-report.json

    # Upload the frontend Trivy scan report as an artifact
    - name: Upload Trivy scan report as artifact - Frontend green
      if: github.event.inputs.rollback_version == ''
      uses: actions/upload-artifact@v4
      with:
        name: frontend-green-trivy-report
        path: frontend-green-trivy-report.json

    # Push the user-api image to Docker Hub
    - name: Push user-api Docker image to Docker Hub
      if: github.event.inputs.rollback_version == ''
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USER_IMAGE_NAME }}:${{ env.VERSION }}

    # Push the voting-api image to Docker Hub
    - name: Push voting-api Docker image to Docker Hub
      if: github.event.inputs.rollback_version == ''
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_VOTING_IMAGE_NAME }}:${{ env.VERSION }}

    # Push the blue frontend image to Docker Hub
    - name: Push frontend blue Docker image to Docker Hub
      if: github.event.inputs.rollback_version == ''
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:blue${{ env.VERSION }}

    # Push the green frontend image to Docker Hub
    - name: Push frontend green Docker image to Docker Hub
      if: github.event.inputs.rollback_version == ''
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:green${{ env.VERSION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

      # allow scaling based on peak hours
    - name: Determine user-api replica count based on time of day
      run: |
        HOUR=$(date +%H)
        if [ "$HOUR" -ge 12 ] && [ "$HOUR" -le 20 ]; then
          echo "Peak hours – using 3 replicas"
          REPLICAS=3
        else
          echo "Off-peak – using 1 replica"
          REPLICAS=1
        fi
        echo "REPLICAS=$REPLICAS" >> $GITHUB_ENV

    - name: Generate terraform.tfvars
      run: |
        echo "user_api_image = \"${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USER_IMAGE_NAME }}:${{ env.VERSION }}\"" > ./terraform/terraform.tfvars
        echo "voting_api_image = \"${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_VOTING_IMAGE_NAME }}:${{ env.VERSION }}\"" >> ./terraform/terraform.tfvars
        echo "frontend_blue_image = \"${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:blue${{ env.VERSION }}\"" >> ./terraform/terraform.tfvars
        echo "frontend_green_image = \"${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_FRONTEND_IMAGE_NAME }}:green${{ env.VERSION }}\"" >> ./terraform/terraform.tfvars
        echo "project_root = \"${{ github.workspace }}\"" >> ./terraform/terraform.tfvars
        # come back to below when directing to new front end
        # echo "active_color = \"green\"" >> ./terraform/terraform.tfvars
        echo "user_api_replicas = ${{ env.REPLICAS }}" >> ./terraform/terraform.tfvars 
    
    - name: Git pull with rebase before tfvars commit
      if: github.event.inputs.rollback_version == ''
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git stash --include-untracked
          git pull --rebase origin master
          git stash pop || echo "No stash to apply"
      
    - name: Commit and push terraform.tfvars
      if: github.event.inputs.rollback_version == ''
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git add -f ./terraform/terraform.tfvars
          git commit -m "Update terraform.tfvars" || echo "Nothing to commit"
          git push origin master 

    - name: Print .tfvars
      run: cat ./terraform/terraform.tfvars

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

     # This is a step to destroy the infrastructure - ensure idempotency
    - name: Terraform Destroy 
      if: github.event.inputs.destroy == 'true'
      working-directory: ./terraform
      run: terraform destroy -auto-approve -var-file="terraform.tfvars"

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve -var-file="terraform.tfvars"

    #- name: Check Prometheus endpoint is live
    #  run: curl -f http://localhost:3000/metrics || exit 1
    
    - name: Notify Slack of finished deployment
      if: github.event.inputs.rollback_version == ''
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
        \"text\": \"*Deployment Finished Notification*\n*Workflow:* ${{ github.workflow }}\n*Status:* ${{ job.status }}\n*Branch:* ${{ github.ref_name }}\n*Initiated by:* ${{ github.actor }}\n*Version:* ${{ env.VERSION }}\"
        }" ${{ secrets.SLACK_WEBHOOK_URL }}

