name: Build and Push to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push user-api
      uses: docker/build-push-action@v5
      with:
        context: ./user-api
        push: true
        tags: lukey721/user-api:latest

    - name: Build and push voting-api
      uses: docker/build-push-action@v5
      with:
        context: ./voting-api
        push: true
        tags: lukey721/voting-api:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./ufc-frontend
        push: true
        tags: lukey721/frontend:latest